module.exports = [
    {
      "firstName": "John",
      "middleName": "Michael",
      "lastName": "Doe",
      "gender": "Male",
      "email": "john.doe@example.com",
      "phoneNumber": "+1234567890",
      "address": "123 Main St, Springfield, IL, 62704",
      "profession": "Software Engineer",
      "hobbies": ["Reading", "Cycling", "Traveling"],
      "motherName": "Mary Doe",
      "fatherName": "Robert Doe",
      "wifeName": "Jane Doe",
      "kids": ["Emily Doe", "Jack Doe"]
    },
    {
      "firstName": "Emma",
      "middleName": "Grace",
      "lastName": "Smith",
      "gender": "Female",
      "email": "emma.smith@example.com",
      "phoneNumber": "+1234567891",
      "address": "456 Elm St, Madison, WI, 53703",
      "profession": "Graphic Designer",
      "hobbies": ["Painting", "Photography", "Yoga"],
      "motherName": "Susan Smith",
      "fatherName": "James Smith",
      "wifeName": null,
      "kids": ["Olivia Smith"]
    },
    {
      "firstName": "David",
      "middleName": "Andrew",
      "lastName": "Johnson",
      "gender": "Male",
      "email": "david.johnson@example.com",
      "phoneNumber": "+1234567892",
      "address": "789 Oak St, Denver, CO, 80203",
      "profession": "Project Manager",
      "hobbies": ["Hiking", "Fishing", "Gardening"],
      "motherName": "Patricia Johnson",
      "fatherName": "William Johnson",
      "wifeName": "Sarah Johnson",
      "kids": ["Lily Johnson", "Sophie Johnson"]
    },
    {
      "firstName": "Sophia",
      "middleName": "Isabella",
      "lastName": "Brown",
      "gender": "Female",
      "email": "sophia.brown@example.com",
      "phoneNumber": "+1234567893",
      "address": "101 Pine St, Austin, TX, 73301",
      "profession": "Marketing Specialist",
      "hobbies": ["Cooking", "Dancing", "Swimming"],
      "motherName": "Linda Brown",
      "fatherName": "Richard Brown",
      "wifeName": null,
      "kids": ["Ethan Brown"]
    },
    {
      "firstName": "James",
      "middleName": "Alexander",
      "lastName": "Williams",
      "gender": "Male",
      "email": "james.williams@example.com",
      "phoneNumber": "+1234567894",
      "address": "202 Cedar St, Seattle, WA, 98101",
      "profession": "Data Analyst",
      "hobbies": ["Gaming", "Chess", "Blogging"],
      "motherName": "Barbara Williams",
      "fatherName": "Charles Williams",
      "wifeName": "Laura Williams",
      "kids": ["Henry Williams"]
    },
    {
      "firstName": "Olivia",
      "middleName": "Sophia",
      "lastName": "Miller",
      "gender": "Female",
      "email": "olivia.miller@example.com",
      "phoneNumber": "+1234567895",
      "address": "303 Maple St, Portland, OR, 97205",
      "profession": "Architect",
      "hobbies": ["Drawing", "Reading", "Running"],
      "motherName": "Elizabeth Miller",
      "fatherName": "Joseph Miller",
      "wifeName": null,
      "kids": ["Ella Miller"]
    },
    {
      "firstName": "Liam",
      "middleName": "Noah",
      "lastName": "Taylor",
      "gender": "Male",
      "email": "liam.taylor@example.com",
      "phoneNumber": "+1234567896",
      "address": "404 Birch St, San Francisco, CA, 94102",
      "profession": "Civil Engineer",
      "hobbies": ["Photography", "Traveling", "Woodworking"],
      "motherName": "Nancy Taylor",
      "fatherName": "David Taylor",
      "wifeName": "Emily Taylor",
      "kids": ["Mason Taylor", "Logan Taylor"]
    },
    {
      "firstName": "Ava",
      "middleName": "Madison",
      "lastName": "Anderson",
      "gender": "Female",
      "email": "ava.anderson@example.com",
      "phoneNumber": "+1234567897",
      "address": "505 Cherry St, Boston, MA, 02108",
      "profession": "HR Manager",
      "hobbies": ["Yoga", "Cooking", "Traveling"],
      "motherName": "Carol Anderson",
      "fatherName": "Thomas Anderson",
      "wifeName": null,
      "kids": ["Luke Anderson"]
    },
    {
      "firstName": "Noah",
      "middleName": "Lucas",
      "lastName": "Thomas",
      "gender": "Male",
      "email": "noah.thomas@example.com",
      "phoneNumber": "+1234567898",
      "address": "606 Walnut St, Miami, FL, 33101",
      "profession": "Financial Analyst",
      "hobbies": ["Running", "Investing", "Cooking"],
      "motherName": "Angela Thomas",
      "fatherName": "Paul Thomas",
      "wifeName": "Isabella Thomas",
      "kids": ["Aiden Thomas", "Evelyn Thomas"]
    },
    {
      "firstName": "Mia",
      "middleName": "Charlotte",
      "lastName": "Martinez",
      "gender": "Female",
      "email": "mia.martinez@example.com",
      "phoneNumber": "+1234567899",
      "address": "707 Spruce St, Los Angeles, CA, 90001",
      "profession": "Teacher",
      "hobbies": ["Reading", "Hiking", "Painting"],
      "motherName": "Dorothy Martinez",
      "fatherName": "Frank Martinez",
      "wifeName": null,
      "kids": ["Harper Martinez"]
    }
    
  ]
  